### ISSUE TITLE
进入页面不会自动刷新

### ISSUE THREAD

**Issue by mf168** [sofach/SFPullRefresh#5]
[[UINavigationBar appearance] setTranslucent:NO];
更改NavigationBar的属性之后   

  [self.tableView sf_addRefreshHandler:^{
    }];

这个方法不会调用了

**Comment by sofach** [comment]
sf_addRefreshHandler需要在[self.view addSubview:self.tableView]之前调用，如果还是有问题可以贴出你的调用代码。
新发了一个版本，修复了一些bug，欢迎提出宝贵意见
